language: node_js
node_js:
  - '0.10'
  - '4'
before_install:
  - npm install -g npm@latest-2
before_deploy:
  - 'git config --global user.email "david+npm@bushong.net"'
  - 'git config --global user.name "David Bushong"'
deploy:
  provider: script
  script: ./node_modules/.bin/nlm release
  skip_cleanup: true
  'on':
    branch: master
    node: '4'
