// Generated by CoffeeScript 1.7.1

/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var Q, assert, clear, emsg, fn, green, name, red, _fn,
  __slice = [].slice,
  __hasProp = {}.hasOwnProperty;

Q = require('q');

assert = require('assertive');

green = function(x) {
  return "\x1B[32m" + x + "\x1B[39m";
};

red = function(x) {
  return "\x1B[31m" + x + "\x1B[39m";
};

clear = "\x1b[39;49;00m";

emsg = function(message, explanation) {
  if (explanation != null) {
    message = "Assertion failed: " + explanation + "\n" + clear + message;
  }
  return message;
};

exports.rejects = function(expln, testee, name) {
  var _ref;
  if (name == null) {
    name = 'rejects';
  }
  if (testee != null) {
    assert.hasType("argument 1 of " + name + " must be a doc string", String, expln);
  } else {
    _ref = [expln, null], testee = _ref[0], expln = _ref[1];
  }
  if (!Q.isPromiseAlike(testee)) {
    if ('function' !== typeof testee) {
      throw new Error("" + name + " expects " + (green('a function or promise')) + " but got " + (red(testee)));
    }
    testee = Q["try"](testee);
  }
  if (name === 'rejects') {
    return testee.then(function() {
      throw new Error(emsg("Promise wasn't rejected as expected to", expln));
    }, function(err) {
      return err;
    });
  } else {
    return testee["catch"](function(err) {
      var _ref1;
      throw new Error(emsg("Promise was rejected despite resolves assertion:\n" + ((_ref1 = err != null ? err.message : void 0) != null ? _ref1 : err), expln));
    });
  }
};

exports.resolves = function(expln, testee) {
  return exports.rejects(expln, testee, 'resolves');
};

_fn = function(name, fn) {
  return exports[name] != null ? exports[name] : exports[name] = function() {
    var args, testee;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (!args.length) {
      return fn();
    }
    testee = args.pop();
    if (Q.isPromiseAlike(testee)) {
      return testee.then(function(val) {
        return fn.apply(null, __slice.call(args).concat([val]));
      });
    } else {
      return fn.apply(null, __slice.call(args).concat([testee]));
    }
  };
};
for (name in assert) {
  if (!__hasProp.call(assert, name)) continue;
  fn = assert[name];
  _fn(name, fn);
}
